ALTER TABLE users
ADD UNIQUE (username);

ALTER TABLE pages
ADD FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT true;

ALTER TABLE sessions
ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
